#%RAML 1.0 NamedExample
value:
  id: 1 
  typeId: 1 
  typeDesc: "home"
  number: "1234"
  street: "blah blah St"
  Unit: "1 a"
  City: "Somewhere"
  StateId: 1
  StateDesc: "WV"
  zipcode: "12345"


